---
# tasks file for mysql
- name: Sets the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present
    # login_unix_socket: /run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    #host_all: yes
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
